import Head from "next/head";
import Image from "next/image";
// import Script from "next/script";
// import Image from "next/image";
import styles from "../styles/Home.module.css";
// import Link from "next/link";


export default function Home() {
  console.log(styles);

  return (
    <div className={styles.container}>
     
      {/* <style jsx>
        {
          `
          h2{
            font-size: 30px;
          }`
        }
      </style> */}

      <Head>
        <title>Welcome to Hunting-Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next , hunting-coder blog" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Script src="/sc.js" strategy="lazyOnload"></Script> */}
      

      <main className={styles.main}>
        <h3 className={styles.title}>
          Welcome to <span className="">Hunting-Coder</span>
        </h3>

        <p className={styles.description}>
          A blog for hunting coder by a hunting coder
        </p>
        {/* <Image className={styles.myimg} src="/coder.avif" width={235} height={158}/> */}
        <Image className={styles.myimg} src="/coder.avif" alt="Hunting-Coder" width={235} height={158}  />

       <div className={styles.container}>
       <div className="blogs">
          <h2 className={styles.latest}>Latest-Blogs</h2>
          <div>
            <h3 className={styles.blogItem}>How to learn java in 2022</h3>
          </div>
        </div>
        
        <div className="blogs">
          <div >
            <h3 className={styles.blogItem}>How to learn Next in 2022</h3>
          </div>
        </div>
        <div className="blogs">
          <div >
            <h3 className={styles.blogItem}>How to learn React.js in 2022</h3>
          </div>
        </div>
       </div>
      </main>
      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
